### ISSUE TITLE
MultiGen installation mysql error

### ISSUE THREAD

**Issue by jukfiuune** [nightflyza/Ubilling#812]
Hello. First of all i would like to say thank you for the amazing software you have made.
Anyways, I was trying to set up MultiGen today with the help your documentation, but when running `mysql -u root -p stg < ./docs/multigen/dump.sql` from the FreeRADIUS3 configuration section, I typed the password in, but i got the following error: 
ERROR 1060 (42S21) at line 175: Duplicate column name 'modifier'
How do I fix this?

**Comment by jukfiuune** [comment]
Forgot to mention, Im using FreeBSD 13.2, and I installed UBilling yesterday, just like in the documentation

**Comment by nightflyza** [comment]
Closed because careless reading of the documentation is not a issue that needs to be resolved.

**Comment by mort1k** [comment]
If you have separate instalation ub+stg and mysql:

It is advisable to upload dumps from the host on which billing is installed, otherwise problems may arise with the backup module when restore VIEWS.  

https://dev.mysql.com/doc/refman/5.7/en/mysqlpump.html#option_mysqlpump_skip-definer
https://stackoverflow.com/questions/9446783/remove-definer-clause-from-mysql-dumps
